### ISSUE TITLE
Postgres connectors should default to trying port 5432 if no port is specified

### ISSUE THREAD

**Issue by jshearer** [estuary/connectors#524] opened 2023-01-26 21:30 UTC
On a call with a user who copied the "endpoint" straight from RDS, turns out if you don't specify a port you get an error rather than the expected default of 5432 being supplied.

We should _probably_ just default to 5432 if you don't specify one. Any reason not to?

**Comment by mdibaiee** [comment] 2023-01-26 21:33
@jshearer the main reason for this has been that network tunnel expects a full address with port, but that only applies if a user is using network tunnel, if they don't, we could provide a default port.

**Comment by williamhbaker** [comment] 2023-09-14 16:56
I tested this out today on RDS and confirmed that if you don't specify a port, both the capture and materialization will work and will default to `5432` implicitly. We've made some changes over the months that I could imagine having this effect (ex: https://github.com/estuary/connectors/commit/3a2398bd324eff906f4d0e05ec96bb04b2401bf5). So, going to close this out, since it doesn't appear to be an issue anymore.

**Closed by williamhbaker** 2023-09-14 16:56 UTC
