### ISSUE TITLE
materialize-bigquery: excessive full table scans

### ISSUE THREAD

**Issue by jgraettinger** [estuary/connectors#125] opened 2022-02-09 20:34 UTC
We've observed that BigQuery does a poor job of avoiding full table scans during the Load phase of materialization transactions, even where the collection key is explicitly selected to allow for much more efficient scans (for example, by using an ascending date as a leading component).

We'd _expect_ that BigQuery would take advantage of min/max ranges over keyed fields to cull the set of micro partitions it must actually process, as Snowflake does, but that's not what we're observing in practice.

**Comment by williamhbaker** [comment] 2023-04-14 13:16
I looked into this recently related to poor BigQuery load phase performance.

The BigQuery materialization creates [clustered tables](https://cloud.google.com/bigquery/docs/clustered-tables) with the clustering columns corresponding to the collection keys.

When doing a load, we stage the keys in a cloud storage object and use a join to query the values (`flow_document`) out of the target table. The join query looks like this for a single binding:

```sql
SELECT 0, l.flow_document
	FROM project.dataset.target_table AS l
	JOIN project.dataset.cloud_storage_ext_table AS r
		 ON l.key1 = r.key2
		 AND l.key1 = r.key2
```

I have observed that this kind of query will indeed scan through all of the data in the target table, regardless of the clustering. This appears to be because the query is comparing the clustered column in the target table to another column value, which [prevents block pruning from being applied](https://cloud.google.com/bigquery/docs/querying-clustered-tables#do_not_compare_clustered_columns_to_other_columns).

This contrasts with a query like the one below which compares a clustered column with a scalar value. This query avoids processing the data for the entire table:

```sql
SELECT l.flow_document
	FROM project.dataset.target_table
	WHERE l.key1 = 'some_value'
```

Aside from the full table scans, there was a larger performance issue during loads caused by using `is not distinct from` for key comparison at the time I looked at this which may or may not have been present when this issue was originally opened.  The load query was changed to use `=` for comparison in https://github.com/estuary/connectors/pull/660. This resolved the major performance bottleneck, but the full table scan behavior remains.

Fundamentally I don't believe there is anything that can be done about the full table scans for the kind of load query we need to do.  There is [some indication](https://cloud.google.com/blog/topics/developers-practitioners/bigquery-explained-working-joins-nested-repeated-data) that clustering may impart a performance benefit in certain circumstances when doing joins but it is unclear to me if this applies to the joins typically performed by a materialization.

I am going to close this out since with the recent change we have gotten join performance to an acceptable level, and because I don't think there is much more we can do to minimize table scanning for BigQuery materializations using standard updates. As it is it may be preferable for very large datasets to use delta updates or longer transaction durations to minimize costs associated with these table scans during load phases.

**Closed by williamhbaker** 2023-04-14 13:16 UTC
