### ISSUE TITLE
Can't delete exchange-rates capture after monthly usage has been exceeded

### ISSUE THREAD

**Issue by psFried** [estuary/connectors#251] opened 2022-06-08 14:39 UTC
Similar to #245 , users are unable to deactivate or delete an exchange-rates capture when their monthly usage has been exceeded. When attempting to deactivate, the logs show an error returned by the connector saying that monthly usage has been exceeded, which blocks the deactivation. Presumably the same error is causing the inability to delete the capture, though in that case the UI only reports a very generic message saying one or more deletions have failed.

**Comment by mdibaiee** [comment] 2022-06-10 17:14
duplicate of https://github.com/estuary/connectors/issues/251

**Closed by mdibaiee** 2022-06-10 17:14 UTC
